TARGET = List deque testWindGauge vector lotto testAccessSet birthday 

all: $(TARGET)

List:
	g++ List.cpp -o List
	
deque:
	g++ deque.cpp -o deque
	
testWindGauge:
	g++ WindGauge.cpp WindGauge.h testWindGauge.cpp -o testWindGauge
	
vector:
	g++ vector.cpp -o vector
	
lotto:
	g++ lotto.cpp -o lotto
	
testAccessSet:
	g++ Access.cpp Access.h testAccessSet.cpp -o testAccessSet
	
birthday:
	g++ birthday.cpp -o birthday
	
clean:
	-rm $(TARGET)