TARGET = freshie_crash scat_a scat_b scat_c

all: $(TARGET)

freshie_crash:
	gcc -o freshie_crash freshie_crash.c

scat_a:
	gcc -o scat_a scat_a.c
	
scat_b:
	gcc -o scat_b scat_b.c
	
scat_c:
	gcc -o scat_c scat_c.c
	
clean:
	-rm $(TARGET)