TARGET = Bucket_Sort Counting_Sort Hollerith Word_Sort

all: $(TARGET)

Bucket_Sortcet_Sort:
	g++ Bucket_Sort.cpp -o Bucket_Sort
	
Counting_Sort:
	g++ Counting_Sort.cpp -o Counting_Sort
	
Hollerith:
	g++ Hollerith.cpp -o Hollerith
	
Word_Sort:
	g++ Word_Sort.cpp -o Word_Sort
	
clean:
	-rm $(TARGET)