TARGET = Longest_Ordered_Subarray Triangle_Sum

all: $(TARGET)

Longest_Ordered_Subarray:
	g++ Longest_Ordered_Subarray.cpp -o Longest_Ordered_Subarray
	
Triangle_Sum:
	g++ Triangle_Sum.cpp -o Triangle_Sum
	
clean:
	-rm $(TARGET)