 /*
CH-230-B
a7 p3.[c]
Cenhan Du
cdu@jacobs-university.de
*/

all : use_linked_list

use_listed_list : link_list.o use_linked_list.o
	gcc -Wall -o use_linked_list link_list.o use_linked_list.o

link_list.o : link_list.h link_list.c
	gcc -Wall -c link_list.c

use_link_list.o : link_list.h use_link_list.c
	gcc -Wall -c use_link_list.o

delete :
	rm -f *.o use_link_list
